test_that("the forces table lists every archive force with area codes", {
  f <- lamp_forces()
  expect_s3_class(f, "tbl_df")
  expect_named(f, c("force_id", "name", "pfa_code", "pfa_name", "country", "notes"))
  expect_equal(nrow(f), 45L)
  expect_false(anyDuplicated(f$force_id) > 0L)
  expect_true(all(grepl("^[a-z]+(-[a-z]+)*$", f$force_id)))
  expect_true(all(c("west-yorkshire", "dyfed-powys", "metropolitan", "btp", "northern-ireland") %in% f$force_id))
  expect_equal(sum(f$country == "england", na.rm = TRUE), 39L)
  expect_equal(sum(f$country == "wales", na.rm = TRUE), 4L)
  expect_equal(sum(f$country == "northern_ireland", na.rm = TRUE), 1L)
  expect_true(is.na(f$pfa_code[f$force_id == "btp"]))
  with_code <- f[!is.na(f$pfa_code), ]
  expect_true(all(grepl("^[EWN][0-9]{8}$", with_code$pfa_code)))
  expect_false(anyDuplicated(with_code$pfa_code) > 0L)
  expect_equal(f$pfa_code[f$force_id == "west-yorkshire"], "E23000010")
  expect_equal(f$pfa_code[f$force_id == "dyfed-powys"], "W15000004")
  expect_equal(f$pfa_name[f$force_id == "city-of-london"], "London, City of")
})

test_that("force names in files and the changelog map to identifiers", {
  expect_equal(lamp_force_id_from_name("West Yorkshire Police"), "west-yorkshire")
  expect_equal(lamp_force_id_from_name("Dyfed-Powys Police"), "dyfed-powys")
  expect_equal(lamp_force_id_from_name("Dyfed Powys Police"), "dyfed-powys")
  expect_equal(lamp_force_id_from_name("Devon and Cornwall Police"), "devon-and-cornwall")
  expect_equal(lamp_force_id_from_name("Devon & Cornwall Police"), "devon-and-cornwall")
  expect_equal(lamp_force_id_from_name("Humberside Constabulary"), "humberside")
  expect_equal(lamp_force_id_from_name("Metropolitan Police"), "metropolitan")
  expect_equal(lamp_force_id_from_name("Metropolitan Police Service"), "metropolitan")
  expect_equal(lamp_force_id_from_name("Thames Valley"), "thames-valley")
  expect_equal(lamp_force_id_from_name("City of London"), "city-of-london")
  expect_equal(lamp_force_id_from_name("British Transport Police"), "btp")
  expect_equal(lamp_force_id_from_name("Police Service of Northern Ireland"), "northern-ireland")
  expect_true(is.na(lamp_force_id_from_name("Gotham City Police")))
  f <- lamp_forces()
  expect_false(anyDuplicated(lamp_force_stem(f$name)) > 0L)
})
